version: '3'


services:
  db:
    container_name: database_moviecatalog
    image: mysql:latest
    volumes:
      - ./database/mysql_data:/var/lib/mysql
      - ./database/init_scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_HOST: '%'
    ports:
      - 127.0.0.1:${DB_PORT}:3306
    expose:
      - "${DB_PORT}"
    networks:
      - network


  adminer:
    container_name: adminer_moviecatalog
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - network
    environment:
      - ADMINER_DEFAULT_SERVER=$DB_HOST

#  app:
#    container_name: app_moviecatalog
#    build:
#      dockerfile: ./Dockerfile
#      context: ./
#    ports:
#      - $APPLICATION_PORT:80
#    restart: unless-stopped
#    networks:
#      - network
#    env_file:
#      - .env


networks:
  network: