version: '3'


services:
  db:
    container_name: database_moviecatalog
    image: mysql:latest
    hostname: $DB_HOST
    volumes:
      - ./database/mysql_data:/var/lib/mysql
      - ./database/init_scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - $DB_PORT:3306
    networks:
      - network


  adminer:
    container_name: adminer_moviecatalog
    image: adminer
    restart: always
    ports:
      - $ADMINER_PORT:8080
    networks:
      - network
    environment:
      - ADMINER_DEFAULT_SERVER=$DB_HOST

#  app:
#    container_name: app_moviecatalog
#    build:
#      dockerfile: ./Dockerfile
#      context: ./
#    ports:
#      - $APPLICATION_PORT:80
#    restart: unless-stopped
#    networks:
#      - network
#    env_file:
#      - .env


networks:
  network: